name: Deploy index.html to EC2

on:
  push:
    paths:
      - 'terraform-node-app/**'
      - 'app/**'
    branches:
      - main
      - feature/Test
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./app ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Start HTTP server (Apache)
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF
            sudo cp -r app/* /var/www/html/
            sudo systemctl restart httpd
          EOF
