name: Terraform Plan & Apply with Manual Approval

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform-node-app/**'
      - 'app/**'
    branches:
      - main
      - feature/Test
  

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      private_key: ${{ secrets.EC2_SSH_KEY }}
      username: ${{ secrets.EC2_USER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-node-app

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./terraform-node-app

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform-node-app

      - name: Run tfsec (Terraform Security Scan)
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform-node-app

      - name: Terraform Apply (Manual Trigger Required)
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
