name: Trivy Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          wget -qO trivy.tar.gz https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.64.1_Linux-64bit.tar.gz
          tar zxvf trivy.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy scan on filesystem
        run: trivy fs . --exit-code 1 --severity CRITICAL,HIGH --no-progress